### ISSUE TITLE
Lambda Invoke method Payload argument should allow str type

### ISSUE THREAD

**Issue by zacholade** [youtype/mypy_boto3_builder#142]
**Describe the bug**
The boto3 lambda client's function, Invoke is currently typed as Union of: `Union[bytes, IO[bytes], StreamingBody]`. While this is correct, a json encoded string is also a perfectly valid argument for this value. 

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.invoke
>Payload (bytes or seekable file-like object) --
The JSON that you want to provide to your Lambda function as input.
>You can enter the JSON directly. For example, --payload '{ "key": "value" }' . You can also specify a file path. For example, --payload file://payload.json .

**To Reproduce**
```py
import json
import boto3
lam = boto3.client("lambda")
lam.invoke(
    FunctionName=MY_LAMBDA_ARN,
    Payload=json.dumps({"foo": "bar"}),
)
```
`pyright <my_file>`
**Actual output**

```
error: Argument of type "str" cannot be assigned to parameter "Payload" of type "bytes | IO[bytes] | StreamingBody" in function "invoke"
    Type "str" cannot be assigned to type "bytes | IO[bytes] | StreamingBody"
      "str" is incompatible with "bytes"
      "str" is incompatible with "IO[bytes]"
      "str" is incompatible with "StreamingBody" (reportGeneralTypeIssues)
```

It is worth noting that this also applies to the body of S3 uploads and the the acm client export_certificates passphrase argument.
```py
import json
import boto3
s3 = boto3.resource("s3")
s3.Object("my_bucket_name", "key").put(
    Body=json.dumps({"foo": "bar"}),
```
**Expected output**

```
No warnings
```

**Additional context**
Your OS: Linux, `boto3-stubs` installation method: `python -m pip install 'boto3-stubs[all]`, `boto3` version `1.21.32

**Comment by vemel** [comment]
Thank you for the report!

I noticed that many S3 methods accept `string` while documentation requires only `bytes`. I think it is safe to change the type to `Union[str, bytes, IO[Any], StreamingBody]`

**Comment by vemel** [comment]
The issue has been fixed in the latest release for all services. I have also added an integration test to cross-check that it works for `s3`.

Please update to the latest `boto3-stubs` and let me know if it works as it should for you.
