### ISSUE TITLE
DynamoDB Table resource's put_item() method has the wrong type for the ConditionExpression parameter

### ISSUE THREAD

**Issue by hnlee** [youtype/mypy_boto3_builder#150]
**Describe the bug**

The `boto3.resource("dynamodb").Table("name").put_item()` method takes a `ConditionExpression` parameter, which according to the `boto3` documentation should be a `boto3.dynamodb.conditions.ConditionBase` object. (See: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Table.put_item)

Currently, in `mypy_boto3_dynamodb.service_resource.Table`, it is annotated as being `str`. (See: https://youtype.github.io/boto3_stubs_docs/mypy_boto3_dynamodb/service_resource/#tableput_item-method)

**To Reproduce**

1. Install `boto3-stubs[...]`
2. Run `mypy`/`pyright` on the following code sample

```python
import boto3
from mypy_boto3_dynamodb.service_resource import Table
from typing import Mapping

def get_table(table_name: str) -> Table:
    return boto3.resource("dynamodb").Table("table_name")

def write_to_table(table: Table, item: Mapping[str, str], condition_attr: str, condition_value: str):
    condition = boto3.dynamodb.conditions.Attr(condition_attr).eq(condition_value)
    table.put_item(Item=item, ConditionExpression=condition)
```

**Actual output**

```
test.py:10: error: Argument "ConditionExpression" to "put_item" of "Table" has incompatible type "Equals"; 
expected "str"
Found 1 error in 1 file (checked 1 source file)
```

**Expected output**

```
Success: no issues found in 1 source file
```

**Additional context**
Mac OS 12.4, `boto3-stubs[dynamodb]==1.24.23` , `boto3==1.24.23`, installed with `pip-tools`

**Comment by vemel** [comment]
Thank you for the report!

Fixed in the latest `mypy-boto3-dynamodb 1.24.27` release. Please update `boto3-stubs` and subpackages. Let me know if it works as it should.
