### ISSUE TITLE
`s3transfer.TransferManager.download()` type annotations are more restrictive than implementation

### ISSUE THREAD

**Issue by kveretennicov** [youtype/mypy_boto3_builder#155]
Implementation allows `str` for `fileobj`: https://github.com/boto/s3transfer/blob/develop/s3transfer/manager.py#L348

But type annotations do not: https://github.com/boto/s3transfer/blob/develop/s3transfer/manager.py#L348

Version: s3transfer/types-s3transfer 0.6.0

**Comment by vemel** [comment]
Thank you for the report. Now, `fileobj` accepts `IO | str | bytes` in all methods and functions. I released `types-s3transfer 0.6.0.post1` with the fix. Please let me know if it works as expected for you.

And please report any other inconsistencies!

**Comment by kveretennicov** [comment]
Thank you!

While testing I ran into `TransferFuture.result` being typed as `-> None`. However, implementation returns `TransferCoordinator.result`, which is typed as `-> str`. I'm not sure which one is correct, but there is some inconsistency here.

**Comment by vemel** [comment]
Project has been moved to a new repo: https://github.com/youtype/types-s3transfer/

**Comment by kveretennicov** [comment]
Everything works now :sparkles:
