### ISSUE TITLE
Problem with TypedDict required params

### ISSUE THREAD

**Issue by mew1033** [youtype/mypy_boto3_builder#159]
Similar to #70, it seems like `InvocationResponseTypeDef` is still giving me the same errors seen in https://github.com/microsoft/pyright/issues/1693. Did that one get missed?

**Comment by vemel** [comment]
Thank you for the report. Please always provide the AWS service name, `lambda` in this case.

`InvocationResponseTypeDef` uses a specific stub to avoid circular TypedDicts. Looks like it is no longer required, so I am going to remove this logic. All keys will be required after the change.

**Comment by vemel** [comment]
Fixed in `mypy-boto3-lambda 1.24.40`. Please let me know if it works as it should.
