### ISSUE TITLE
Security Issue with your package from pypi.org

### ISSUE THREAD

**Issue by rakovskij-stanislav** [youtype/mypy_boto3_builder#162]
Hello! Found a security issue in your package in pypi:
https://pypi.org/project/boto3-stubs/

Affected versions of package:
- 1.24.11 (Jun 17, 2022)
- 1.24.12 (Jun 17, 2022)
- 1.24.13 (Jun 20, 2022)
- 1.24.14 (Jun 21, 2022)
- 1.24.15 (Jun 22, 2022)
- 1.24.16 (Jun 23, 2022)

There's an unmet dependency on module `mypy-boto3-redshiftserverless` if you will try to install these versions of `boto3-stubs` with extras `all`:

```
>python -m pip install --upgrade boto3-stubs[all]==1.24.16
Collecting boto3-stubs[all]==1.24.16
  Downloading boto3_stubs-1.24.16-py3-none-any.whl (46 kB)
     ---------------------------------------- 46.8/46.8 kB 1.1 MB/s eta 0:00:00
Collecting typing-extensions>=4.1.0
  Downloading typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting botocore-stubs
  Downloading botocore_stubs-1.27.46-py3-none-any.whl (44 kB)
     ---------------------------------------- 44.1/44.1 kB 2.1 MB/s eta 0:00:00
...
Collecting mypy-boto3-memorydb<1.25.0,>=1.24.0
  Downloading mypy_boto3_memorydb-1.24.36.post1-py3-none-any.whl (28 kB)
ERROR: Could not find a version that satisfies the requirement mypy-boto3-redshiftserverless<1.25.0,>=1.24.0; extra == "all" (from boto3-stubs[all]) (from versions: none)
ERROR: No matching distribution found for mypy-boto3-redshiftserverless<1.25.0,>=1.24.0; extra == "all"
```

It happens because there is missed requirement in `setup.py` file:
```python
...
    install_requires=[
        "botocore-stubs",
        "typing-extensions>=4.1.0",
    ],
    extras_require={
        "all": [
            "mypy-boto3-accessanalyzer>=1.24.0, <1.25.0",
            "mypy-boto3-account>=1.24.0, <1.25.0",
            "mypy-boto3-acm>=1.24.0, <1.25.0",
...
            "mypy-boto3-redshift-data>=1.24.0, <1.25.0",
            "mypy-boto3-redshiftserverless>=1.24.0, <1.25.0",
...

```

It's dangerous because the intruder can create malicious package `mypy-boto3-redshiftserverless` on pypi and:
- Make online guides how to use your package and abuse this malicious supply chain attack to compromise users
- Infect automated CI/CD pipelines that uses old version of your package
- Infect other users by hardcoding those versions of package in opensource projects that use it

It's dangerous because usage of `boto3-stubs`, even quite outdated, is not something strange. Everyone likes hardcoded versions of packages, even in the era of protestware.

The best solution is to delete exact versions of package from pypi. Better to break dependencies in some old pipelines than compromise them.

Also suggest you to set security email address for reporting this type of vulnerabilities: `https://github.com/youtype/mypy_boto3_builder/security/advisories`

Rakovsky Stanislav (Positive Technologies)

**Comment by vemel** [comment]
Yes, unfortunately I had to remove the package because botocore changed service name to redshift-serverless , and pypi does not accept packages with similar names.

I can potentially create post releases for all these versions

**Comment by rakovskij-stanislav** [comment]
Post-releases are also good solution in this type of situation.

Also it would be great to register a CVE for this. CVEs would help security teams on customer side to properly execute vulnerability management process.

About non-accepting packages with similar names: 28 of July I have reported about package names requesys, that mimirty requests, this way idk about strictity of typosquatting politics)

Rakovsky Stanislav (Positive Technologies)

**Comment by vemel** [comment]
let me try to upload the packages now

**Comment by vemel** [comment]
```
ERROR WARNING  Error during upload. Retry with the --verbose option for more details.                                         
ERROR ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                
ERROR          The name 'mypy-boto3-redshiftserverless' is too similar to an existing project. See                            
ERROR          https://pypi.org/help/#project-name for more information.
```

**Comment by vemel** [comment]
So, I believe, the intruder cannot upload `mypy-boto3-redshiftserverless` due to PyPI restrictions. However, `boto3-stubs[all]==1.24.11` installation is still broken. I will try to find a proper way.

**Comment by rakovskij-stanislav** [comment]
The functionality of prohibitation: https://github.com/pypi/warehouse/blob/39daea188d2e1e6494c50753cd48cb5a8da3e8c4/warehouse/utils/project.py#L124

Can you try to register "mypy.boto3.redshiftserverless" instead of "mypy-boto3-redshiftserverless"? For pypi it's the similar names, but not for sql) If it will be success, it would be interesting bypass of collision check.

**Comment by vemel** [comment]
I have released post releases for all affected packages, which require `mypy-boto3-redshift-serverless` instead of `mypy-boto3-redshiftserverless`:

```
INFO [1/2] Published boto3_stubs_package 1.24.11.post1
INFO [2/2] Published boto3_stubs_lite_package 1.24.11.post2
INFO [1/2] Published boto3_stubs_package 1.24.12.post1
INFO [2/2] Published boto3_stubs_lite_package 1.24.12.post1
INFO [1/2] Published boto3_stubs_package 1.24.13.post1
INFO [2/2] Published boto3_stubs_lite_package 1.24.13.post1
INFO [1/2] Published boto3_stubs_package 1.24.14.post1
INFO [2/2] Published boto3_stubs_lite_package 1.24.14.post1
INFO [1/2] Published boto3_stubs_package 1.24.15.post1
INFO [2/2] Published boto3_stubs_lite_package 1.24.15.post1
INFO [1/2] Published boto3_stubs_package 1.24.16.post1
INFO [2/2] Published boto3_stubs_lite_package 1.24.16.post1
```

Please let me know if it solves the issue or if anything is left to be done. Thank you for the report!

**Comment by rakovskij-stanislav** [comment]
Great!

This vulnerability was found as a part of my research at Positive Technologies for making open sourse projects more secure.

So to make the processes of secure development more smooth, I suggest you:

1. To set an email for security vulnerabilities issues here: https://github.com/youtype/mypy_boto3_builder/security/policy
Good example: https://github.com/apache/activemq/security/policy

2. Register a CVE for this vulnerability. CVE would help security teams on customer side to properly execute vulnerability management process and demonstrates that you are seriously take information security. Also I will be happy)

**Comment by vemel** [comment]
Thank you for taking a look at my project! Will do this today.

**Comment by vemel** [comment]
@rakovskij-stanislav I have added a security report.

Could you please guide me through the process of reporting a CVE? As far as I understand, I should do it [here](https://www.cve.org/ResourcesSupport/ReportRequest). However, I have no idea whom to select as a CNA.

**Comment by rakovskij-stanislav** [comment]
Your project is opensource and you don't belong to Amazon (right?), so your CVE Numbering Authority is MITRE Corporation (https://www.cve.org/PartnerInformation/ListofPartners/partner/mitre)
