### ISSUE TITLE
sqs get_queue_attributes() has the wrong type for AttributeNames

### ISSUE THREAD

**Issue by sodul** [youtype/mypy_boto3_builder#165]
**Describe the bug**
The boto3 documentation clearly state that `AttributeNames` has over 20 valid values, but mypy_boto3 is giving it the QueueAttributeFilterType literals which only has 10 different values.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Client.get_queue_attributes

**To Reproduce**

1. Install `boto3-stubs[sqs]`
2. Run `mypy`/`pyright` on the following code sample

```python
import boto3

import mypy_boto3_sqs

sqs_client: mypy_boto3_sqs.Client = boto3.client('sqs')
sqs_client.get_queue_attributes(QueueUrl='anything', AttributeNames=('LastModifiedTimestamp',))

```
Argument "AttributeNames" to "get_queue_attributes" of "SQSClient" has incompatible type "Tuple[str]"; expected "Sequence[Literal['AWSTraceHeader', 'All', 'ApproximateFirstReceiveTimestamp', 'ApproximateReceiveCount', 'MessageDeduplicationId', 'MessageGroupId', 'SenderId', 'SentTimestamp', 'SequenceNumber', 'SqsManagedSseEnabled']]"  [arg-type] (7:41)
```

In mypy_boto3_sqs.client.pyi:
```python
    def get_queue_attributes(
        self, *, QueueUrl: str, AttributeNames: Sequence[QueueAttributeFilterType] = ...
    ) -> GetQueueAttributesResultTypeDef:
```
should be:
```Python
    def get_queue_attributes(
        self, *, QueueUrl: str, AttributeNames: Sequence[QueueAttributeNameType] = ...
    ) -> GetQueueAttributesResultTypeDef:
```

**Additional context**
macOS 12.5.1, Python 3.10.6.

```
pip install boto3==1.24.59 'boto3-stubs[sqs]==1.24.59'
```

**Comment by vemel** [comment]
Thank you for the report! Will check.

**Comment by sodul** [comment]
I tried the example on an older machine with `mypy-boto3-sqs==1.21.34` and did not get an error, so it seems to be a regression.

**Comment by vemel** [comment]
This is related to https://github.com/aws/aws-sdk/issues/310 botocore bug. I will try to provide a better temp fix on my side.

**Comment by vemel** [comment]
Fixed in `mypy-boto3-sqs1.24.60`.

Please check and let me know if it works as it should.

**Comment by sodul** [comment]
@vemel it worked for me. Thanks for the quick turnaround!
