### ISSUE TITLE
boto3.setup_default_session has wrong return type

### ISSUE THREAD

**Issue by chuckwondo** [youtype/mypy_boto3_builder#167]
**Describe the bug**

The return type for `boto3.setup_default_session` (in `mypy_boto3_builder/stubs_static/boto3/__init__.pyi`) is defined as `Session`, but it should be `None` because the function has no explicit return statement (thus implicitly returning `None`).

**Comment by vemel** [comment]
Thank you, I will include this fix in the next release.

**Comment by vemel** [comment]
Fixed in `boto3-stubs 1.24.60.post1` and `boto3-stubs-lite 1.24.60.post1`.

Please check and let me know if it works as it should.
