### ISSUE TITLE
Reading attributes from aioboto3 object

### ISSUE THREAD

**Issue by takeda** [youtype/mypy_boto3_builder#168]
**Describe the bug**
So one of recent updates started throwing following error:
```
error: Incompatible types in "await" (actual type "Literal['available', 'deregistered', 'error', 'failed', 'invalid', 'pending', 'transient']", expected type "Awaitable[Any]")
```

The code in question:
```python
    async with session.resource("ec2") as ec2:
        image = await ec2.Image(parsed_event.dest_ami)
        if await image.state == "pending":   <--- this line throws an error
```

My understanding is that attributes might have been added recently and while this type is correct for boto3, aioboto3 requires to await the property to get the value.

It's confusing and not well documented, but that's the only way I made it work. It also makes sense as the object fetches data lazily.

**To Reproduce**

install `types-aioboto3[ec2,organizations,secretsmanager,stepfunctions,lambda,sts] == 9.6.0.post2`
install `mypy==0.971`

**Additional context**
OS X, poetry, boto3==1.21.21

**Comment by vemel** [comment]
Hello! Thank you for the report.

Looks like, I completely overlooked async properties in aioboto3. I will try to find a proper solution.

**Comment by vemel** [comment]
I made all Resource attributes `Awaitable`. I am going to test this today and release all `aiobotocore/aioboto3` services.

**Comment by vemel** [comment]
Sorry for the delay, my changes look good, so I will release today.

**Comment by vemel** [comment]
@takeda @johman10 I have just updated all `aiobotocore` services with the fix included. Please updated to `types-aiobotocore-s3/sqs 2.4.0.post1` and let me know if it works as it should.

**Comment by takeda** [comment]
@vemel I just tried, and it resolved my issue, so I'm closing the ticket.

Thank you.

**Comment by johman10** [comment]
Hmm.. It didn't seem to work for me. I will open a new issue for my case, perhaps they are different things after all.
