### ISSUE TITLE
Best practices for keeping `boto3-stubs` and `boto3` in sync?

### ISSUE THREAD

**Issue by jfly** [youtype/mypy_boto3_builder#173]
## Some context

The [README on pypi.org for `boto3-stubs`](https://pypi.org/project/boto3-stubs/) says:

> boto3-stubs version is the same as related boto3 version and follows [PEP 440](https://www.python.org/dev/peps/pep-0440/) format.

It took me a while to find where this comes from. I believe it's autogenerated by: https://github.com/youtype/mypy_boto3_builder/blob/aa37cb484d7d339b13ed20ad3a641c40b654938d/mypy_boto3_builder/templates/common/footer.md.jinja2#L36-L37

## The problem

The version synchronicity between `boto3` and `boto3-stubs` has made it easy for us to manually get `boto3-stubs` in sync with boto3 when things drift. However, it would be nice if we could keep these in sync without any human intervention. For the record, we use poetry, and we used to write our pyproject.toml to look something like this:

```
[tool.poetry.dependencies]
boto3 = "*"
boto3-stubs = {extras = ["essential", "sns"], version = "*"}
```

However, if someone runs a `poetry update boto3` to pull in the latest version of `boto3`, this can cause drift with whatever version of boto3-stubs we happen to have. So, we've started either explicitly setting the exact same version for both boto3 and boto3-stubs, or just setting boto3-stubs to whatever version of boto3 poetry resolved to. Both of these approaches feel less than great: humans will keep having to get involved to keep the two in sync.

## One idea
Have y'all considered specifying an `install_requires` on the exact version of boto3 that boto3-stubs was built for? Right now I don't see boto3 listed at all: https://github.com/youtype/mypy_boto3_builder/blob/aa37cb484d7d339b13ed20ad3a641c40b654938d/mypy_boto3_builder/templates/boto3-stubs/setup.py.jinja2#L48-L52

That would give a tool like poetry enough information to know that it can't upgrade `boto3` without also upgrading `boto3-stubs`.

**Comment by vemel** [comment]
Hello!

This is good idea. However, `boto3-stubs` does not depend on `boto3` directly. The reason behind it to decrease a chance of a potential dependency hell. E. g. `awscli` depends on a specific `boto3` version, therefore most projects keep `awscli` installation outside of project venv.

In most cases, you can use the latest `boto3-stubs` with any `boto3` version. Inconsistencies should be quite small. Or you could always update both librarie3s explicitly

```
poetry update boto3 boto3-stubs
```

Please let me know what you think. I do not have a good solution right now.

**Comment by jfly** [comment]
@vemel, that makes a lot of sense. Could this be achieved with pythons support for "extras"? I'm thinking something like `boto3-stubs[boto3]`, which would add that dependency on an exact version of boto3.

**Comment by vemel** [comment]
@jfly good idea! I will add this functionality and test it. However, there is another caveat. Service supported methods and arguments actually depend on `botocore` version installed, not `boto3` version. So I think it makes sense to depend on an exact version of `boto3` and `botocore`.

**Comment by jfly** [comment]
That sounds great, @vemel. Thanks!

**Comment by vemel** [comment]
@jfly did you have a chance to try it out? Please let me know.

**Comment by hoffmanr-cshs** [comment]
adding my +1 to this issue and to the proposed solution - this is going to be great for our team!

I just tested it out, and got this result:

```
# in pyproject.toml:
#   requires-python = "~=3.9"
#   dependencies = [..., "boto3 == 1.26.33"] # arbitrarily pinned a version for testing
#   project.optional-dependencies.dev = [...,"boto3-stubs[boto3,essential]"]
$ pip intstall -e .[dev]
$ pip freeze | grep boto
boto3==1.26.33
boto3-stubs==1.26.33
botocore==1.29.33
botocore-stubs==1.29.39
[...]
```

I do see a diversion between the versions of `botocore` and `botocore-stubs`, but `boto3` and `boto3-stubs` are staying in sync. Not sure if this is intended / expected / even an issue, but it's already a big improvement over having to keep everything pinned to one old version. Thanks for working on this!

**Comment by vemel** [comment]
`botocore-stubs` is static (not generated by `mypy_boto3_builder`) and no longer directly related to this project, even though it is a direct dependency of `boto3-stubs`.

**Comment by jfly** [comment]
@vemel, I just had an opportunity to test this out today, and things work great. Thanks again! I think we can close this issue.

**Comment by lg-kialo** [comment]
@vemel I was trying to figure out if there's a way to prevent the version divergence for `botocore-stubs` that was mentioned in the [comment above](https://github.com/youtype/mypy_boto3_builder/issues/173#issuecomment-1367524011) and stumbled upon your comment. I'm confused by 

> botocore-stubs is static (not generated by mypy_boto3_builder) and no longer directly related to this project

since https://pypi.org/project/botocore-stubs/ says the package is part of this project.

Do you mind clarifying that?
