### ISSUE TITLE
MypyStub doesn't recognize Decimal

### ISSUE THREAD

**Issue by Mowinski** [youtype/mypy_boto3_builder#179]
**Describe the bug**
When I run mypy on this code snipped I got this error
```
Argument "Item" to "put_item" of "Table" has incompatible type "Dict[str, object]"; expected "Mapping[str, Union[bytes, bytearray, str, int, Decimal, bool, Set[int], Set[Decimal], Set[str], Set[bytes], Set[bytearray], Sequence[Any], Mapping[str, Any], None]]"  [arg-type]
```

**To Reproduce**

1. Install `boto3-stubs[...]`
2. Run `mypy`/`pyright` on the following code sample

```    def save_location(
        self,
        history_id: HistoryID,
        latitude: float,
        longitude: float,
        accuracy: float,
        timestamp: int,
    ):
        item = {
            "history_id": str(history_id),
            "activity_id": str(uuid.uuid4()),
            "location": {
                "latitude": self._make_decimal(latitude),
                "longitude": self._make_decimal(longitude),
            },
            "accuracy": self._make_decimal(accuracy),
            "timestamp": timestamp,
        }
        boto3.resource(
            "dynamodb",).Table("measurements").put_item(Item=item)

    @staticmethod
    def _make_decimal(value: float) -> Decimal:
        return Decimal(str(value))
...
```

**Additional context**
Windows Machine with poetry

**Comment by vemel** [comment]
Thank you for the report!

I do not think that this is because of `Decimal`, because `Decimal` is accepted as `Item` mapping value. You can check if `HistoryID.__str__` method returns a string, this could be an issue. Otherwise, I would try to comment `item` keys one by one and find a conflicting value this way.

Let me know if this helps.

**Comment by Mowinski** [comment]
Hi :) I've double checked and it works when I comment all decimal property. HistoryID is a UUID field.

**Comment by vemel** [comment]
Well, I still cannot reproduce it with Decimals. It would be helpful if you could send a small sample that I can run to reproduce the issues.

**Comment by vemel** [comment]
You can create a new branch and try to reproduce this bug here: https://github.com/youtype/stubs-playground
