### ISSUE TITLE
import mypy_boto3_s3 failing in python 3.8: 'ABCMeta' object is not subscriptable

### ISSUE THREAD

**Issue by ringohoffman** [youtype/mypy_boto3_builder#191]
**Describe the bug**

This error just randomly started failing all my python 3.8 builds even though I'm not consuming the latest version:

```
    import mypy_boto3_s3
../../opt/anaconda3/envs/glass38/lib/python3.8/site-packages/mypy_boto3_s3/__init__.py:41: in <module>
    from .client import S3Client
../../opt/anaconda3/envs/glass38/lib/python3.8/site-packages/mypy_boto3_s3/client.py:39: in <module>
    from .paginator import (
../../opt/anaconda3/envs/glass38/lib/python3.8/site-packages/mypy_boto3_s3/paginator.py:35: in <module>
    from .type_defs import (
../../opt/anaconda3/envs/glass38/lib/python3.8/site-packages/mypy_boto3_s3/type_defs.py:592: in <module>
    "Callback": Callable[..., Any],
E   TypeError: 'ABCMeta' object is not subscriptable
```

The issue is at type definition:

**mypy_boto3_s3/type_defs.py**:

```python
_OptionalBucketDownloadFileRequestTypeDef = TypedDict(
    "_OptionalBucketDownloadFileRequestTypeDef",
    {
        "ExtraArgs": Dict[str, Any],
        "Callback": Callable[..., Any],  # <- here
        "Config": TransferConfig,
    },
    total=False,
)
```

I'm really confused about how this ever would have worked in Python 3.8 or why it started failing now of all times. I think this could easily be fixed by rewriting the class like this:

```python
from typing import Any, Callable, Dict, TypedDict

class _OptionalBucketDownloadFileRequestTypeDef(TypedDict, total=False):
    ExtraArgs: Dict[str, Any]
    Callback: Callable[..., Any]
    Config: TransferConfig
```

I'm not sure if there are other instances of this in the type_defs. Would really appreciate a fast fix.

**To Reproduce**

```console
$ conda create -n my_env python=3.8
$ pip install boto3-stubs[s3]==1.26.21
```

```python
import mypy_boto3_s3
```

**Comment by vemel** [comment]
Thank you for the report. SHould be fixed in `boto3-stubs 1.26.96.post1`. Please update and let me know if everything works as expected.

**Comment by ringohoffman** [comment]
@vemel `1.26.96.post1` is not working for me. I was able to fix it locally by using `import from typing` in
1. `mypy_boto3_s3/type_defs.py`
2. `mypy_boto3_s3/client.py`
3. `mypy_boto3_s3/service_resource.py`

**Comment by vemel** [comment]
Yes, looks like I rebuilt packages for an older version of `boto3`, but did not for the latest. WIll do.

**Comment by kmurphy4** [comment]
@vemel I assume this is what you're fixing right now, but it looks like `boto3-stubs 1.26.97.post1` has the same bug.  If I look at the sdist via

```
$ wget https://files.pythonhosted.org/packages/64/d1/82d18231c1c92f6d7eecc3bb13999935886fb7be949b888ce19af105c245/boto3-stubs-1.26.97.post1.tar.gz 
$ tar xzf boto3-stubs-1.26.97.post1.tar.gz
$ grep 'generated with mypy.boto3.builder' boto3-stubs-1.26.97.post1/setup.py 
    description="Type annotations for boto3 1.26.97 generated with mypy-boto3-builder 7.13.0",
```
(and 7.13.0 doesn't include the fix in https://github.com/youtype/mypy_boto3_builder/commit/02fcb39de23c3a494280957d1f44c603e079e07e).

**Comment by vemel** [comment]
Just released:

```
mypy-boto3-s3 1.26.97.post1
mypy-boto3-dynamodb 1.26.97.post1
mypy-boto3-ec2 1.26.97.post1
mypy-boto3-rds 1.26.97.post1
```

Imports should work now.

Regarding `boto3-stubs 1.26.97.post1` - it is not affected, only service packages are affected. Please update and try again.

**Comment by kmurphy4** [comment]
Thanks! That works for me :)

**Comment by ringohoffman** [comment]
I had been installing `mypy_boto3_s3` via `boto3-stubs[s3]`, which is still not working for python 3.8. I can switch to `mypy-boto3-s3`, but I imagine some users will continue to be affected.
