### ISSUE TITLE
Question on inheritance

### ISSUE THREAD

**Issue by yiannis-zen** [youtype/mypy_boto3_builder#194]
Hi!
Apologies if it's a noob question but wanted to confirm if the stubs provided would assist us in our use-case.
One of the types provided by the project is `RunJobFlowInputRequestTypeDef`
We were thinking to create a python class which extends it to populate with some defaults we frequently use.
Roughly we want to do something like this:
```
class EmrCluster(RunJobFlowInputRequestTypeDef):
    """
    Doesn't work as intended to define a default name and set of instances when
    an EmrCluster instance when initialized
    """
    def __init__(self):
        super().__init__()
        self['Name'] = 'test'
        self['Instances'] = JobFlowInstancesConfigTypeDef()


emr.run_job_flow(**EmrCluster())
```

But doesn't work as we expected. Is there any other way we can approach this?
Thanks again!

**Comment by vemel** [comment]
Hello!

[RunJobFlowInputRequestTypeDef](https://youtype.github.io/boto3_stubs_docs/mypy_boto3_emr/type_defs/#runjobflowinputrequesttypedef) is not a regular class, it is a TypedDict: https://peps.python.org/pep-0589/#inheritance

However, it looks like you do not need to inherit from `RunJobFlowInputRequestTypeDef`, you just want to pass kwargs to `emr.run_job_flow`. So, let's use a regular `dict`, but annotate it as `RunJobFlowInputRequestTypeDef` to check types properly.

```python
from mypy_boto3_emr.type_defs import RunJobFlowInputRequestTypeDef

run_job_flow_request: RunJobFlowInputRequestTypeDef = {
   "Name": "test",
   "Instances": {}
}

emr.run_job_flow(**run_job_flow_request)
```

Let me know if this helps!

**Comment by vemel** [comment]
@yiannis-zen let me know if this approach works for you.

**Comment by yiannis-zen** [comment]
Thanks @vemel for getting back to me!
This approach would work, but that way we don't get the autompletion/linting goodies right?

**Comment by vemel** [comment]
Well, `pylance` provides code completion for TypedDicts ( it could be better though :-) ). so you should be good. Type checking also works as long as you have explicit type annotation for kwargs param: `run_job_flow_request: RunJobFlowInputRequestTypeDef`. For example if you provide a key that is not accepted or a wrong value type, you should see an error from `mypy` or `pyright`.

However, type checking does not work for `emr.run_job_flow(**run_job_flow_request)`, so you can pass any dictionary here and type checker will ignore it. This is why we set an explicit type annotation for `run_job_flow_request`
