### ISSUE TITLE
`InstanceTypeDef` gone in `mypy-boto3-ec2==1.28.3.post1`

### ISSUE THREAD

**Issue by kmurphy4** [youtype/mypy_boto3_builder#206]
**Describe the bug**
In the latest release of `mypy-boto3-ec2`, the `type_defs.InstanceTypeDef` symbol is gone, though it existed in previous releases.

**To Reproduce**
```sh
$ python3.8 -m pip install 'mypy-boto3-ec2==1.28.3.post1'  # same for `boto3-stubs[ec2]`
$ python3.8 -c 'from mypy_boto3_ec2.type_defs import InstanceTypeDef'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'InstanceTypeDef' from 'mypy_boto3_ec2.type_defs' (/tmp/freshvenv/lib/python3.8/site-packages/mypy_boto3_ec2/type_defs.py)
```
but it exists in `1.28.3`:
```sh
$ python3.8 -m pip install 'mypy-boto3-ec2==1.28.3'  # same for `boto3-stubs[ec2]`
$ python3.8 -c 'from mypy_boto3_ec2.type_defs import InstanceTypeDef'
```

**Additional context**
```sh
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

$ python3.8 --version
Python 3.8.0

$ python3.8 -m pip --version
pip 23.1.2 from /tmp/freshvenv/lib/python3.8/site-packages/pip (python 3.8)

$ python3.8 -m pip freeze | grep boto3
boto3==1.28.3
boto3-stubs==1.28.3.post1
mypy-boto3-ec2==1.28.3.post1
```

**Comment by vemel** [comment]
Thank you for the report.

This hotfix will be released in two hours.

**Comment by vemel** [comment]
And, it is here!

Just released `mypy-boto3-ec2 1.28.3.post2` with the fix included. Please test it and let me know if it works as it should.

Also, many other packages were updated, check [7.15.0 release notes](https://github.com/youtype/mypy_boto3_builder/releases/tag/7.15.0).

**Comment by mbalc** [comment]
well, this is the second time this package breaks my hourly cron job

now that I adapted my codebase to use the Output thingy, now they're gone again :v

**Comment by vemel** [comment]
@mbalc yes, please revert. Sorry for the inconvenience. 

`OutputTypeDef`s are only created if there are corresponding incompatible input `TypeDef`s.

**Comment by kmurphy4** [comment]
Thanks! This is working for me :)
