### ISSUE TITLE
Shorten package descriptions for compatibility with Azure DevOps mirroring, pipelines

### ISSUE THREAD

**Issue by kevinnowland** [youtype/mypy_boto3_builder#215]
**Describe your idea**

Package descriptions are very long, which causes issues when installing if the package has been mirrored in an azure devops artifact feed. This behavior has been observed elsewhere, e.g., this [azure-cli package issue](https://github.com/Azure/azure-cli/issues/18383).

Putting this as a feature request instead of a bug since code is working, but can be hard to install. Not sure that is appropriate.

**Code sample**

I have no code sample to provide.

**Additional context**

I have been affected by this in particular when running `pip install boto3-stubs[ec2]` which also causes issues with `boto3-stubs[essential]`.

**Comment by vemel** [comment]
Hello! Thank you for the report.

I can easily drop TypeDefs list from a package readme to make it shorter. 

 Should be done this week.

**Comment by vemel** [comment]
Fixed. I re-released all essential packages. I removed lists of service Literals and TypeDefs and added links to online docs instead.

- `mypy-boto3-cloudformation 1.28.19`
- `mypy-boto3-dynamodb 1.28.19`
- `mypy-boto3-ec2 1.28.19.post1`
- `mypy-boto3-lambda 1.28.19`
- `mypy-boto3-rds 1.28.19`
- `mypy-boto3-s3 1.28.19`
- `mypy-boto3-sqs 1.28.19`

Please test it and let me know if it works as it should.
