### ISSUE TITLE
upload_fileobj types in S3Client are wrong.

### ISSUE THREAD

**Issue by caner-cetin** [youtype/mypy_boto3_builder#218]
```python
    def upload_fileobj(
        self,
        Fileobj: FileobjTypeDef,
        Bucket: str,
        Key: str,
        ExtraArgs: Dict[str, Any] = ...,
        Callback: Callable[..., Any] = ...,
        Config: TransferConfig = ...,
    ) -> None:
```

This function contradicts to
```python
S3.Client.upload_fileobj(Fileobj, Bucket, Key, ExtraArgs=None, Callback=None, Config=None)
```

meaning ExtraArgs, Callback, Config is not optional in stub files, thus leading to errors. Latest version of stubs, boto3, everything.

**Comment by vemel** [comment]
Thank you for the report.

Yes, looks like this function is injected by `boto3`, so it should be manually annotated. I will release a fix this week.

**Comment by vemel** [comment]
Fix in the latest release. Please update to `mypy-boto3-s3 1.28.27` and let me know if it works as it should.

**Comment by caner-cetin** [comment]
@vemel it works as expected now. thanks matey!
