### ISSUE TITLE
GetKeyPolicyResponseTypeDef Policy should be `str` not `Dict[str, Any]`

### ISSUE THREAD

**Issue by sodul** [youtype/mypy_boto3_builder#223]
**Describe the bug**
After upgrading to from boto3 1.28.25 to 1.28.37, and the matching stubs we get an error on the types returned by KMS `get_key_policy()`.

The type is `GetKeyPolicyResponseTypeDef` with a 'Policy` key typed as `Dict[str, Any]`.
```
GetKeyPolicyResponseTypeDef = TypedDict(
    "GetKeyPolicyResponseTypeDef",
    {
        "Policy": Dict[str, Any],
        "ResponseMetadata": ResponseMetadataTypeDef,
    },
)
```

While the policy is json encoded and that content is a dict, the type is actually `str`.

I tested it and confirmed the return type:
```
>>> kms.get_key_policy(KeyId='ad13a324-4bf6-4f7c-877a-5b0d5a32ce36', PolicyName='default')
{'Policy': '{\n  "Version" : "2012-10-17",\n  "Statement" : [
```

**To Reproduce**

1. Install `boto3-stubs[kms]`
2. Run `mypy` on the following code sample:

```python
import boto3
session = boto3.Session()
kms = session.client('kms')
policy_id = 'ad13a324-4bf6-4f7c-877a-5b0d5a32ce36'
policy: str = kms.get_key_policy(KeyId=policy_id, PolicyName='default')
```

**Actual output**

```
incompatible type "dict[str, Any]"; expected "str"
```

**Expected output**

no error

**Additional context**
OS: macOS 13.5.1, Python 3.11.5.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kms/client/get_key_policy.html#

**Comment by sodul** [comment]
Further details.

With `pip install mypy-boto3-kms==1.28.16` we have `str`:

```
GetKeyPolicyResponseTypeDef = TypedDict(
    "GetKeyPolicyResponseTypeDef",
    {
        "Policy": str,
        "ResponseMetadata": ResponseMetadataTypeDef,
    },
)
```

With `pip install mypy-boto3-kms==1.28.16` we have:
```
GetKeyPolicyResponseTypeDef = TypedDict(
    "GetKeyPolicyResponseTypeDef",
    {
        "Policy": Dict[str, Any],
        "ResponseMetadata": ResponseMetadataTypeDef,
    },
)
```

I hope this helps.

**Comment by vemel** [comment]
Released fixed packages:

- `mypy-boto3-acm 1.28.37`
- `mypy-boto3-acm-pca 1.28.37`
- `mypy-boto3-alexaforbusiness 1.28.37`
- `mypy-boto3-chime 1.28.37`
- `mypy-boto3-chime-sdk-identity 1.28.37`
- `mypy-boto3-chime-sdk-messaging 1.28.37`
- `mypy-boto3-comprehend 1.28.37`
- `mypy-boto3-iam 1.28.37`
- `mypy-boto3-kms 1.28.37`
- `mypy-boto3-lookoutequipment 1.28.37`
- `mypy-boto3-marketplace-catalog 1.28.37`
- `mypy-boto3-mediastore 1.28.37`
- `mypy-boto3-rekognition 1.28.37`
- `mypy-boto3-securityhub 1.28.37`
- `mypy-boto3-servicecatalog-appregistry 1.28.37`
- `mypy-boto3-servicecatalog 1.28.37`
- `mypy-boto3-sso-admin 1.28.37`
- `mypy-boto3-sts 1.28.37`
- `mypy-boto3-transfer 1.28.37`

Please update and let me know if it works as it should.

**Comment by sodul** [comment]
Thank you for the fix!
