### ISSUE TITLE
`s3.Object.copy_from` is missing dict type for `CopySource` parameter

### ISSUE THREAD

**Issue by Kache** [youtype/mypy_boto3_builder#308]
**Describe the bug**
In [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/object/copy_from.html) the `s3.Object.copy_from` supports a union of string and dict:

```py
    CopySource='string' or {'Bucket': 'string', 'Key': 'string', 'VersionId': 'string'},
```

However in the latest type stub (`mypy-boto3-s3 1.34.138`) there's only `str`:

```py
        CopySource: str,
```

**To Reproduce**

1. Install `boto3-stubs[essential]`
2. Run `mypy`/`pyright` on the following code sample

```python
import boto3

boto3.resource('s3').Object('foo', 'bar').copy_from(CopySource={'Bucket': 'bar', 'Key': 'foo'})
```

**Actual output**

```
test.py
  test.py:3:64 - error: Argument of type "dict[str, str]" cannot be assigned to parameter "CopySource" of type "str" in function "copy_from" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations
```

**Expected output**

```
0 errors, 0 warnings, 0 informations
```

**Additional context**
Very similar issue as https://github.com/youtype/mypy_boto3_builder/issues/169

**Comment by vemel** [comment]
Hello! Thank you for the report.

Looks like `CopySource` argumet type annotation is incorrect for `Object.copy_from` and `ObjectSummary.copy_from`.

**Comment by vemel** [comment]
Fixed in the latest `mypy_boto3_builder 7.15.3` verison. Also, I released `mypy-boto3-s3 1.34.158` with the fix included. Please update and let me know if it works as it should.

**Comment by Kache** [comment]
works! this was the change? https://github.com/youtype/mypy_boto3_builder/commit/8ea21503e200b11dd6ac3d524b91794328c3af5f

and thanks!

**Comment by vemel** [comment]
Yes. As you see, I was overriding `copy`/`copy_from` for multiple resources already, but `Object` and `ObjectSummary` were not covered.
