### ISSUE TITLE
Request: Explain the difference between `types-boto3`, `boto3-stubs` and `mypy-boto3`

### ISSUE THREAD

**Issue by Avasam** [youtype/mypy_boto3_builder#314]
It's not clear to me which distribution I should be using if I want stubs for the `boto3` package.

My first assumption is that the 3 packages should essentially be the same, but the metadata (including the description) slightly differ in each and there's no explanation why.

Looks like `types-*` is created to be similar to typeshed's notation, `mypy-*` for users who might be searching "mypy boto3" and `boto3-stubs` the most canonical package (as it will have the same name as the package doesn't look like it's coming from typeshed)

Looking at https://github.com/youtype/.github/blob/main/profile/README.md I wanna say `boto3-stubs`

**Comment by vemel** [comment]
Hello! Yes, it makes sense to clarify it in README and package description on PyPI.

- `boto3-stubs` - main package, provides all AWS services as extras. this is the only package that I recommend to install in project's documentation
- `types-boto3` - proxy package to install `boto3-stubs`m createdd to be similar to `typeshed`
- `mypy-boto3` - another proxy package. I added it to replace old package that was need to generate dynamic parts on typ annotations. No longer needed.

I think I will update description on PyPi for `types-boto3` and `mypy-boto3`.

**Comment by Avasam** [comment]
Thanks for the answer! Going for `boto3-stubs` as I originally guess then.

**Comment by vemel** [comment]
I will keep this issue open until I change readmes.
