### ISSUE TITLE
[docs] ImagebuilderClient signature change

### ISSUE THREAD

**Issue by BwL1289** [youtype/mypy_boto3_builder#320]
**Describe the bug**
The signature for `imagebuilderClient` changed to `ImagebuilderClient` but it hasn't been updated in the docs.

**To Reproduce**

1. Install `types-aiobotocore-imagebuilder`

```python
from types_aiobotocore_imagebuilder.client import imagebuilderClient
```

See import error.

It needs to be:

```python
from types_aiobotocore_imagebuilder.client import ImagebuilderClient
```

**Comment by vemel** [comment]
Hello!

Thank you for the report. Docs for `aiobotocore` services were not updated due to an error in Jinja templates. The error is fixed, so I am going to regenerate docs for `aiobotocore` and `aioboto3`.

**Comment by vemel** [comment]
Should be good now: https://youtype.github.io/types_aiobotocore_docs/types_aiobotocore_imagebuilder/client/

Please cross-check and let me know if the issue is resolved.

**Comment by BwL1289** [comment]
LGTM!
