### ISSUE TITLE
[stepfunctions] Results of DescribeExecution inaccurate for differ execution statuses

### ISSUE THREAD

**Issue by taesungh** [youtype/mypy_boto3_builder#321]
The response of [DescribeExecution in AWS Step Functions](https://docs.aws.amazon.com/step-functions/latest/apireference/API_DescribeExecution.html) can vary based on the status of the given execution.

The current output type `DescribeExecutionOutputTypeDef` (for [`SFN.Client.describe_execution`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/stepfunctions/client/describe_execution.html)) specifies all items as required which is partly contradictory.
```python
DescribeExecutionOutputTypeDef = TypedDict(
    "DescribeExecutionOutputTypeDef",
    {
        "executionArn": str,
        "stateMachineArn": str,
        "name": str,
        "status": ExecutionStatusType,
        "startDate": datetime,
        "stopDate": datetime,
        "input": str,
        "inputDetails": CloudWatchEventsExecutionDataDetailsTypeDef,
        "output": str,
        "outputDetails": CloudWatchEventsExecutionDataDetailsTypeDef,
        "traceHeader": str,
        "mapRunArn": str,
        "error": str,
        "cause": str,
        "stateMachineVersionArn": str,
        "stateMachineAliasArn": str,
        "redriveCount": int,
        "redriveDate": datetime,
        "redriveStatus": ExecutionRedriveStatusType,
        "redriveStatusReason": str,
        "ResponseMetadata": ResponseMetadataTypeDef,
    },
)
```

#### Example query and potential responses
```python
import boto3
sfn_client = boto3.client("stepfunctions")
history = sfn_client.describe_execution(executionArn="arn:...")
```

<details>
<summary><h5>For status <code>RUNNING</code></h5></summary>

```python
{
    "executionArn": "arn:...",
    "stateMachineArn": "arn:...",
    "name": "...",
    "status": "RUNNING",
    "startDate": datetime.datetime(...),
    "input": '{...}',
    "inputDetails": {"included": True},
    "redriveCount": 0,
    "redriveStatus": "NOT_REDRIVABLE",
    "redriveStatusReason": "Execution is RUNNING and cannot be redriven",
    "ResponseMetadata": { ... },
}
```
</details>

<details>
<summary><h5>For status <code>SUCCEEDED</code></h5></summary>

```python
{
    "executionArn": "arn:...",
    "stateMachineArn": "arn:...",
    "name": "...",
    "status": "SUCCEEDED",
    "startDate": datetime.datetime(...),
    "stopDate": datetime.datetime(...),
    "input": '{...}',
    "inputDetails": {"included": True},
    "output": '{...}',
    "outputDetails": {"included": True},
    "redriveCount": 0,
    "redriveStatus": "NOT_REDRIVABLE",
    "redriveStatusReason": "Execution is SUCCEEDED and cannot be redriven",
    "ResponseMetadata": { ... },
}
```
</details>

<details>
<summary><h5>For status <code>FAILED</code></h5></summary>

```python
{
    "executionArn": "arn:...",
    "stateMachineArn": "arn:...",
    "name": "...",
    "status": "FAILED",
    "startDate": datetime.datetime(...),
    "stopDate": datetime.datetime(...),
    "input": '{...}',
    "inputDetails": {"included": True},
    "traceHeader": "...",
    "error": "Error",
    "cause": "...",
    "redriveCount": 0,
    "redriveStatus": "REDRIVABLE",
    "ResponseMetadata": { ... },
}
```
</details>

<details>
<summary><h5>For status <code>TIMED_OUT</code></h5></summary>

```python
{
    "executionArn": "arn:...",
    "stateMachineArn": "arn:...",
    "name": "...",
    "status": "TIMED_OUT",
    "startDate": datetime.datetime(...),
    "stopDate": datetime.datetime(...),
    "input": '{...}',
    "inputDetails": {"included": True},
    "traceHeader": "...",
    "redriveStatus": "NOT_REDRIVABLE",
    "redriveStatusReason": "Execution's redrivable period has ended",
    "ResponseMetadata": { ... },
}
```
</details>

<details>
<summary><h5>For status <code>ABORTED</code></h5></summary>

```python
{
    "executionArn": "arn:...",
    "stateMachineArn": "arn:...",
    "name": "...",
    "status": "ABORTED",
    "startDate": datetime.datetime(...),
    "stopDate": datetime.datetime(...),
    "input": '{...}',
    "inputDetails": {"included": True},
    "traceHeader": "...",
    "redriveStatus": "REDRIVABLE",
    "ResponseMetadata": { ... },
}
```
</details>

And there is also status `PENDING_REDRIVE` for which I don't have an example.

#### Resolution
It would be great if this builder could produce a union of narrowed variants although it may be difficult to account for all possible scenarios. Otherwise, marking certain fields as `NotRequired` would suffice. Specifically, it appears `stopDate`, `output`, `outputDetails`, `error`, `cause`, `traceHeader`, and `redriveStatusReason` are all possibly not included in the response along with `mapRunArn`, `redriveDate`, `stateMachineAliasArn`, and `stateMachineVersionArn`.

#### Additional context
Referencing [mypy-boto3-stepfunctions v1.35.46](https://pypi.org/project/mypy-boto3-stepfunctions/1.35.46/)

**Comment by vemel** [comment]
Hello!

Thank you for the report. Unfortunately, there is no way to check totality of output shapes. However, it is possible to override a type parsed from `botocore` shapes and provide a union of potential output `TypedDicts`.

You could help me by writing  all possible `DescribeExecution...OutputTypeDef`s here in a comment. Let me know if you are interested in adding  an override for `SFN.Client.describe_execution` return type as a PR.

**Comment by vemel** [comment]
For now I decided to avoid massive changes, because `builder` does not support `TypedDict` -> `Union` substitution.
Instead, I improved logc for marking output `TypedDict` keys and `NotRequired`. So, `DescribeExecutionOutputTypeDef` should have correct totality in the next release.

**Comment by vemel** [comment]
Fixed in the latest release: https://github.com/youtype/mypy_boto3_builder/releases/tag/8.2.0

Pleas eudpate and let me know if it works as expected.
