### ISSUE TITLE
Wrong type for `aioboto3` resource context manager

### ISSUE THREAD

**Issue by kpark-hrp** [youtype/mypy_boto3_builder#325]
**Describe the bug**

Currently the `aioboto3` type generator creates the following _incorrect_ type hint (snippet from `aioboto3-stubs/session.pyi`).
```python
@overload
def resource(
    self,
    service_name: Literal["dynamodb"],
    region_name: Optional[str] = ...,
    api_version: Optional[str] = ...,
    use_ssl: Optional[bool] = ...,
    verify: Union[bool, str, None] = ...,
    endpoint_url: Optional[str] = ...,
    aws_access_key_id: Optional[str] = ...,
    aws_secret_access_key: Optional[str] = ...,
    aws_session_token: Optional[str] = ...,
    config: Optional[Config] = ...,
) -> DynamoDBServiceResource: ...
```

**To Reproduce**

The proper `aioboto3` usage is the following where `dynamodb: DynamoDBServiceResource`
```python
async with aioboto3.Session().resource("dynamodb") as dynamodb:
    table = await dynamodb.Table(TABLE_NAME)
```

The current type hint generator makes it seem like following is also possible because type checker will think that `dynamodb: DynamoDBServiceResource`. But it is NOT possible since the `.resource()` returns `ResourceCreatorContext` type that needs to go through `await __aenter__()` before it becomes `DynamoDBServiceResource` type. Thus, this will cause a run-time error.
```python
dynamodb = faioboto3.Session().resource("dynamodb")
table = await dynamodb.Table(TABLE_NAME)
```

**Solution**

The correct type hint would be something along the lines of the following. `DynamoDBServiceResource` itself should not be an async context manager.
```python
@overload
def resource(
    self,
    service_name: Literal["dynamodb"],
    region_name: Optional[str] = ...,
    api_version: Optional[str] = ...,
    use_ssl: Optional[bool] = ...,
    verify: Union[bool, str, None] = ...,
    endpoint_url: Optional[str] = ...,
    aws_access_key_id: Optional[str] = ...,
    aws_secret_access_key: Optional[str] = ...,
    aws_session_token: Optional[str] = ...,
    config: Optional[Config] = ...,
) -> ResourceCreatorContext[DynamoDBServiceResource]: ...
```

**Additional context**

```
types-aioboto3[aioboto3,dynamodb,s3]==13.2.0
```

**Comment by vemel** [comment]
Thank you for the report! I will test this change and include it to the next release.

**Comment by vemel** [comment]
Fixed in `main`. I will check if everything works as expected and release it later today or tomorrow. If you have time - you can help me by building `types-aioboto3` manually and verify if it works:

```bash
# clone git repo
git clone git@github.com:youtype/mypy_boto3_builder.git
cd mypy_boto3_builder

# this will create mypy_boto3_output/types_aioboto3_stubs_package with ready to install package
# you might need uv: https://docs.astral.sh/uv/getting-started/installation/
uv run python -m mypy_boto3_builder mypy_boto3_output --product aioboto3 --no-smart-version

# install types-aioboto3 to active Python env
python mypy_boto3_output/types_aioboto3_package/setup.py install
```

THen, you can run type checker on your project.

Thank you!

**Comment by kpark-hrp** [comment]
Thank you @vemel for quickly working on this! It works like a charm for `aioboto3.Session().resource()`.

But one more thing, I think you need to do the same for `aioboto3.Session().client()` because it returns `ClientCreatorContext[GenericClient]`. For example,
```python
s3_client_context: ClientCreatorContext[S3Client] = aioboto3.Session().client("s3")
```

**Comment by vemel** [comment]
Makes sense. This is not directly related to `aioboto3`, but it is what `aiobotocore` does. I will fix it as well. Thank you for testing my changes!

**Comment by kpark-hrp** [comment]
@vemel Thanks for the release, but I don't think a new [types-aioboto3](https://pypi.org/project/types-aioboto3/) has been released yet. When will a new version be released to Pypi?

**Comment by vemel** [comment]
Hello! I just released 

- types-aioboto3-lite 13.2.0.post2
- types-aioboto3 13.2.0.post2
- types-aiobotocore-lite 2.15.2.post3
- types-aiobotocore 2.15.2.post3

with the fix included. Could you please test if it works as expected and let me know?

**Comment by kpark-hrp** [comment]
Just checked with the following newly published package. Works. Thank you!
```
types-aioboto3 13.2.0.post2
types-aiobotocore 2.15.2.post3
```

**Comment by kpark-hrp** [comment]
Unrelated to this issue, I noticed that the source `.tar.gz` is no longer being published. Not an issue for me but wanted to bring up to make sure that this is intentional.
<img width="373" alt="image" src="https://github.com/user-attachments/assets/46e09e02-6c6f-44ad-952b-4bb0aee871b4">

**Comment by vemel** [comment]
Good call! Fixed release script, published `*.tar.gz` packages for `types-aioboto3` and `types-aiobotocore`.

**Comment by kpark-hrp** [comment]
Looks great. I am assuming that this `ResourceCreatorContext[]` one is still outstanding? https://github.com/youtype/mypy_boto3_builder/issues/325#issuecomment-2499909229

**Comment by vemel** [comment]
> Looks great. I am assuming that this `ResourceCreatorContext[]` one is still outstanding? [#325 (comment)](https://github.com/youtype/mypy_boto3_builder/issues/325#issuecomment-2499212471)

No, `ResourceCreatorContext[]` has been added as well to all `session.resource` methods. Do you still have issues?

**Comment by kpark-hrp** [comment]
Ah I meant `ClientCreatorContext` for `session.client` methods.

**Comment by vemel** [comment]
It was also fixed. It is part of `aiobotocore`, not `aioboto3` itself. 

https://github.com/youtype/types-aiobotocore/blob/main/aiobotocore-stubs/session.pyi#L60

**Comment by kpark-hrp** [comment]
Ah I see that you fixed `create_client()` under `aiobotocore`. I think you also need to fix `client()` in `aioboto3.Session()`, no?

This snippet is from `aioboto3-stubs/session.pyi`
```python
    @overload
    def client(
        self,
        service_name: Literal["secretsmanager"],
        region_name: Optional[str] = ...,
        api_version: Optional[str] = ...,
        use_ssl: Optional[bool] = ...,
        verify: Union[bool, str, None] = ...,
        endpoint_url: Optional[str] = ...,
        aws_access_key_id: Optional[str] = ...,
        aws_secret_access_key: Optional[str] = ...,
        aws_session_token: Optional[str] = ...,
        config: Optional[Config] = ...,
    ) -> SecretsManagerClient: ...
```

**Comment by vemel** [comment]
You are right. I added `ClientCreatorContext` for `types-aiobotocore`, but I forgot that `types-aioboto3` also generates annotations for `session.client` and overrides `types-aiobotocore`.

I just fixed static stubs at https://github.com/youtype/types-aioboto3/ . I should update generator as well.

**Comment by vemel** [comment]
Fixed in the latest builder release. I released packages with the fix included:

- `types-aioboto3 13.2.0.post3`
- `types-aioboto3-lite 13.2.0.post3`

Please let me know if the issues is solved.

**Comment by kpark-hrp** [comment]
Just tested. The issue seems to be fixed now. Thanks!
