### ISSUE TITLE
joserfc depedency of cognitoidp stubs not installed

### ISSUE THREAD

**Issue by dhensen** [youtype/mypy_boto3_builder#326]
**Describe the bug**
joserfc does not get installed, not sure if this is a boto3-stubs issue or pdm issue, please help

**To Reproduce**

See isolated example: https://github.com/dhensen/boto3-stub-joserfc-issue
There is code that uses the library in test_proof.py it will trigger the error. Log is included in the README.md

**Comment by vemel** [comment]
Thank you for the report.

For now service packages do not have service-specific dependencies. However, this is a good idea to add this functionality.

**Comment by dhensen** [comment]
Thank you so much @vemel. I see it now... I must have had sudden blindness when looking at that traceback. Thanks for helping me out, I can confirm installing `moto[cognitoidp]` solves this for me.

Also good to know explicitly that service packages do not have dependencies 👍 

Have a nice day and once again thanks for helping out!
