### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Omri-Ben-Yair** [youtype/mypy_boto3_builder#336]
**Describe the bug**
Recently the type annotations changed from using typing **Dict** to just **dict**, this breaks support for python 3.8

The bug was introduced in mypy-boto3-glue = 1.35.87, it did not exists in 1.35.80, so probably introduced  on Dec 12 by this [commit](https://github.com/youtype/mypy_boto3_builder/commit/3a99f5815b4a70295f4588bea90341b4096c67e4)

Only python > 3.9 support **dict** in type annotations.

The type looks like:
```
class RecipeActionOutputTypeDef(TypedDict):
    Operation: str
    Parameters: NotRequired[dict[str, str]]
```

**To Reproduce**

1. install mypy-boto3-glue = "1.35.87"
2. try to import a type which uses a dict like SchemaVersionListItemTypeDef, it will get an error on import phase

```python
from mypy_boto3_glue.type_defs import SchemaVersionListItemTypeDef
...
```

**Actual output**

```
Traceback (most recent call last):
    from mypy_boto3_glue.type_defs import SchemaVersionListItemTypeDef
  File "project1/.venv/lib/python3.8/site-packages/mypy_boto3_glue/__init__.py", line 79, in <module>
    from .client import GlueClient
  File "project1/.venv/lib/python3.8/site-packages/mypy_boto3_glue/client.py", line 28, in <module>
    from .paginator import (
  File "project1/.venv/lib/python3.8/site-packages/mypy_boto3_glue/paginator.py", line 88, in <module>
    from .type_defs import (
  File "project1/.venv/lib/python3.8/site-packages/mypy_boto3_glue/type_defs.py", line 1863, in <module>
    "Parameters": NotRequired[dict[str, str]],
TypeError: 'type' object is not subscriptable
```

**Additional context**
Mac OS, python 3.8.16.
mypy-boto3-glue = 1.35.87

**Comment by vemel** [comment]
Hello! Thanks you for the report. All TypeDefs now use py39+ type annotations.

It is recommended to put `mypy_boto3_*` import into `TYPE_CHECKING`. This way you can make it work on py38, since all popular type checkers support subscriptable types.

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
   from mypy_boto3_glue.type_defs import SchemaVersionListItemTypeDef
```

If you use TypeDefs for something else, e. g., inheritance or runtime checks, add a fallback:

```python
if TYPE_CHECKING:
   from mypy_boto3_glue.type_defs import SchemaVersionListItemTypeDef
else:
   SchemaVersionListItemTypeDef = object
```

Let me knowif this works for you, or if you have a scenario in which it does not work.

**Comment by Omri-Ben-Yair** [comment]
Thanks for the clarification @vemel.
Shouldn't the library state that it only supports py39+? (https://pypi.org/project/boto3-stubs/)

**Comment by Omri-Ben-Yair** [comment]
Thanks for the clarification @vemel .

**Comment by vemel** [comment]
@Omri-Ben-Yair With the latest `mypy-boto3-glue` release you can use types in runtime on Python 3.8 like before. Please let me know if it works.
