### ISSUE TITLE
`types-aiobotocore[s3]` requires `boto3`

### ISSUE THREAD

**Issue by dmkulazhenko** [youtype/mypy_boto3_builder#337]
**Describe the bug**
Generated `types_aiobotocore_s3/client.py` on line 27 looks like:
```python
from boto3.s3.transfer import TransferConfig
```
which obviously leads to ImportError as far as boto3 is not required for either aiobotocore or types-aiobotocore packages.
(seems to be it's accidental import as far as none of boto3 should be used here :thinking:)

**To Reproduce**

```bash
~/.pyenv/versions/3.12.4/bin/python -m venv venv
source venv/bin/activate

pip install types-aiobotocore[s3] aiobotocore

python -c "import types_aiobotocore_s3"
```

**Actual output**

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/.../Temp/venv/lib/python3.12/site-packages/types_aiobotocore_s3/__init__.py", line 49, in <module>
    from .client import S3Client
  File "/home/.../Temp/venv/lib/python3.12/site-packages/types_aiobotocore_s3/client.py", line 27, in <module>
    from boto3.s3.transfer import TransferConfig
ModuleNotFoundError: No module named 'boto3'
```

**Additional context**
Your OS, `types-boto3` installation method, `boto3` version, etc.
Os: 6.1.112-1-MANJARO / Ubuntu 22/23/24 / Amazon Linux 2
Installation method: pip / uv
Pip freeze:
```
aiobotocore==2.16.1
aiohappyeyeballs==2.4.4
aiohttp==3.11.11
aioitertools==0.12.0
aiosignal==1.3.2
attrs==24.3.0
botocore==1.35.88
botocore-stubs==1.35.88
frozenlist==1.5.0
idna==3.10
jmespath==1.0.1
multidict==6.1.0
propcache==0.2.1
python-dateutil==2.9.0.post0
six==1.17.0
types-aiobotocore==2.16.1
types-aiobotocore-s3==2.16.1
types-awscrt==0.23.6
urllib3==2.3.0
wrapt==1.17.0
yarl==1.18.3
```

**Comment by vemel** [comment]
Thank you for the bug report. Yes, imports in `client.pyi/py` should use try-expect fallback. I will fix it in the upcoming release.

**Comment by vemel** [comment]
Fixed in the latest release: https://github.com/youtype/mypy_boto3_builder/releases/tag/8.7.1

Please update and let me know if it works as expected.

**Comment by dmkulazhenko** [comment]
@vemel, it works for me, thanks for quick fix :heart:
