### ISSUE TITLE
types-aioboto3 requests invalid types-aiobotocore-* version

### ISSUE THREAD

**Issue by dacevedo12** [youtype/mypy_boto3_builder#338]
**Describe the bug**
`types-aioboto3 = { extras = ["batch", "bedrock-runtime", "dynamodb", "ec2", "marketplace-entitlement", "meteringmarketplace", "s3", "sqs", "sts"], version = "13.3.0"}`

`Because types-aioboto3 (13.3.0) depends on types-aiobotocore-sts (>=13.3.0,<13.4.0) which doesn't match any versions, types-aioboto3 is forbidden`

**Additional context**
Installed via poetry

**Comment by vemel** [comment]
THank you for the report. Yes, types-aiobotocore-sts version should be different, e.g. `2.16.1`. However, it is strange that I ebven put a specific version requirement. I will check and fix it.

**Comment by vemel** [comment]
Fixed in the latest release: https://github.com/youtype/mypy_boto3_builder/releases/tag/8.7.1

Please update and let me know if it works as expected.

**Comment by dacevedo12** [comment]
Fixed, thanks!!
